apiVersion: v1
kind: Pod
metadata:
  labels:
    run: icmp-responder
    networkservicemesh.io/app: "icmp-responder"
    networkservicemesh.io/impl: "icmp-responder"
  name: icmp-responder
  namespace: default
spec:
  containers:
  - args:
    - /bin/sh
    env:
      - name: NSM_LISTEN_ON_URL
        value: /var/lib/networkservicemesh/nsm.client.io.sock
      - name: NSM_CONNECT_TO_URL
        value: /var/lib/networkservicemesh/nsm.server.io.sock
    image: fkautz/icmp-responder:0.0.8
    imagePullPolicy: IfNotPresent
    name: icmp-responder
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    resources:
      limits:
        networkservicemesh.io/socket: 1
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-control-plane
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
